/*
 * Copyright (C) 2003 - 2013 OpenSubsystems.com/net/org and its owners. All rights reserved.
 * 
 * This file is part of OpenSubsystems.
 *
 * OpenSubsystems is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>. 
 */
 
package org.opensubsystems.pattern.issue.data;

/**
 * Enumeration representing various severity issues
 * 
 * @author bastafidli
 */
public enum Severity
{
   /**
    * Fatal error that caused system to exit and stop functioning in order to
    * prevent further issues.
    */
   FATAL("Fatal error", 100),
   /**
    * Exception generated and caught by the system.
    */
   EXCEPTION("Exception", 150),
   /**
    * Error detected by the system that caused or could cause some problems. 
    */
   ERROR("Error", 200),
   /**
    * Warning generated by the system to notify the viewer of some situation or
    * condition.
    */
   WARNING("Warning", 300);
    
   // Attributes ///////////////////////////////////////////////////////////////

   /**
    * Name of the severity.
    */
   protected String m_strName;
   
   /**
    * Weight of the severity.
    */
   protected int m_iWeight;
    
   // Logic ////////////////////////////////////////////////////////////////////

   /**
    * Non public constructor as required by the enum spec.
    * 
    * @param strName - name of the severity
    * @param iWeight - weight of the severity
    */
   Severity(
      String strName,
      int    iWeight
   )
   {
       m_strName = strName;
       m_iWeight = iWeight;
   }
   
   public String getName(
   )
   {
       return m_strName;
   }
   
   public int getWeight(
   )
   {
       return m_iWeight;
   }
}
